.\" This man page for getprocess
.TH getprocess "1" "2021-03-20" "getprocess 01.01" "User Commands"
.SH NAME
getprocess
.SH SYNOPSIS
.B getprocess - get virtal machines infos
.br
.B getprocess [--batch | -b] - disable GUI mode
.br
.B getprocess [--verbose] - verbose mode (if not in GUI mode)
.br
.B getprocess [--csv] - enable csv output (if not in GUI mode)
.br
.B getprocess [--url=... --token=... --OStable=... --NETtable=...] - enable the upload to HarperDB (Replace "..." with the value(s)) (if not in GUI mode)
.br
.SH DESCRIPTION
Gestore di processi e thread in Windows
.SH AUTHORS
Castellani Davide: owner